channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - librosa=0.9.2
  - tqdm=4.64.1
  - requests=2.28.2
  - colorama=0.4.6
  - ansiwrap=0.8.4
  - pyyaml=6.0
  - dataclassy=1.0.1
  - kaldi=5.5.1016
  - sox=14.4.2
  - ffmpeg=5.1.2
  - pynini=2.1.5
  - openfst=1.8.2
  - baumwelch=0.3.7
  - setuptools_scm=66.1.0
  - ngram=1.3.14
  - praatio=5.1.5
  - biopython=1.80
  - sqlalchemy=1.4.46
  - montreal-forced-aligner=2.0.6
